language: node_js
node_js:
- 8.9.4
branches:
  only:
  - master
  - dev
before_script:
- npm install -g ionic cordova jest
notifications:
  webhooks:
    urls:
    - https://hooks.glip.com/webhook/6d688e2d-f076-4521-8213-f2479e99afe6
    on_success: change
    on_failure: always
    on_start: change
script:
- npm run test-ci
deploy:
  provider: heroku
  api_key:
    secure: ejq0CAGf3hniAscKe+j3U0WnvDmRIoISCy26Jb5yJLVaBfZKQGvEkm/3QR3/+fN3Eqzgbvtn+K/ZyguPDp1eiQHYctMda2nMdfJA8J7aPKm2wtiyBIf0l1UPH/eVzA2gERgO39ztxfJPN8++rwHdPZNDdAnIbRIIEa+w6vS4/foNVVSTaArsQtFs2IrjexgFd1spdHA4Bg7q0/lpVpD7kIBFuDFrsElfZEqCjh9cbbnL3twbzqfdm2pxFGv333KjsLw0plrnsSUWpZIpXGHyPkX6f/oxJ5laQuN6My10iiVj2i1sMXqkq4hQP2Fmepy9bvBg1Biv2hqQANfrf8Bf32E8GstVvhkzdgKXhVoZ5Btsw2ZNRd0Cebtvj0w+V/y4ZCn9YUop4YdI9SuibUOAJ9qqM1dBLUYak22f+jSmsJaLzzwqEafUc9oPwK65di1fP0DcPbqtJDs3zQdc3RnEJvDU8ZJ3Khtxi0C+WJbZPX3Ak/wukW00UmYM0E5zNtDKtbbrmCthwJsIhXunP6yPOUj340kUCg3E9ZqGcIKJ5aljvTKHoxRfFYzuJi1SekFmeFLbDv9DAqjos9dvoPIFJAIA2nxcOugZs6vKbFJ5kDV8gACfSbx9CErcPAY4FEkyVZ6eK6kBIkQPM1jMHrswbjD+YxmeROLtS1pqErv9lk8=
  app: ssf-reboot
  on:
    repo: SoftStackFactory/reboot
