language: node_js
node_js:
- 8.9.4
branches:
  only:
  - master
  - dev
before_script:
- npm install -g ionic cordova jest
notifications:
  webhooks:
    urls:
    - https://hooks.glip.com/webhook/6d688e2d-f076-4521-8213-f2479e99afe6
    on_success: change
    on_failure: always
    on_start: change
script:
- npm run test-ci
deploy:
  provider: heroku
  api_key:
    secure: "pEkJnH/54iYzFPuymZKaxsDPbmEEXDzEPKwnjAkrNkCv1PEjJwYdA5cu1v89pw5fN7+saIARhGFyHSai0zaMCG6m0hY5BLPnDMiJ65NyDuAsmygONxOBe6FLhwMeJKQ7EmN/aRenq7+hCxWKVW9nkZRA8FQL7VW1WiqASYS8uFnJphsEcFEn6IoRZZbnmG/KhRAaGKSzefcwsp0vXFhE/pTahpqmw+lA7kgylCmqZUicRLcMVZGVHPUFV/TLf2DzkaikLsHjro+cGdEyYLQHn7b2+TxmN/6bpi4ZstKt9Lpthdphu1SlaRIgXlKWfNIUPkJJHFFnTekaIZuVFN3CwQ3fZlCT9i448qUGsWsn8rmzI89PHfdTD4CZNFKwgFJO1P1lTAZyB6ozCsfr9tUz3Ga+CS+RgZ4EfFiBqhPDWMBOTzPZAWXaYPZ+W9rHtYAkeL+o4lTtal+BFNn6VSRXvAHJqRVZAUAe6k0EqtOM+piFsFOLnwhq2gleDWcu/JrizTPofmnqU6UiuZ+G9erEXpEcZ/3DWCjvVw08kKVLovsHmdN6nB3pI0bV1kEhzjWsbg/6G1/ASgTsQotjYeqckWJYiCtpzmtsU+q6quG924NmQwsuPehh7GOXD3+LszpNfRpetGGebKL04Dfd1HM/EwsHADpzSSMThUPYzasnqVg="
  app: ssf-reboot
  on:
    repo: SoftStackFactory/reboot
